### ISSUE TITLE
Support LLVM 6.0 and LLVM7 SVN and needs CLRadeonExtender 0.1.7

### ISSUE THREAD

**Issue by oscarbg** [matszpk/mesa3d-comp-bridge#3]
Hi,
building it with LLVM6.0rc and LLVM7 build has minor issues..
so seems needs LLVM5.0 right now..

also should note that needs  CLRadeonExtender 0.1.5 or later is false even using 0.1.6 fails with some AmdCL2..HeaderEnd64 undefined struct so I used 0.1.7git..

**Comment by matszpk** [comment]
Now, mesa3d-comp-bridge requires new CLRadeonExtender. I found bug in my AMD OpenCL 2.0 binary format handling: my code didn't support vectypehint and work_size_group_hint, so I added these features to new CLRadeonExtender. However, some changes was needed in same mesa3d-comp-bridge to correctly read kernel arguments. Please use new CLRadeonExtender to ensure better support for AMD OpenCL 2.0 binary format. README will be updated later.
